### ISSUE TITLE
Select a SongCard from the search Sidebar to add to the TracklistTable

### ISSUE THREAD

**Issue by Kokuyo3** [Kokuyo3/harmonic-mixing-helper#1]
**Feature Description:** As a user, I should be able to add songs from the search Sidebar to the TracklistTable by clicking them.

```
Given I search for a song in the Sidebar
When I click a SongCard result
Then I should see it added to the TracklistTable
And I should see the search results refresh and show related songs based on the song I selected
```
```
Given I have selected songs from the search Sidebar
When I click the button to remove a tracklist Item
Then I should see it removed from the TracklistTable
And I should see the search results refresh and show related songs based on the last song in the tracklist
And I should see the harmonic keys suggestion card
```
```
Given I have selected songs from the search Sidebar
When I click the button to move a tracklist Item up/down
Then I should see it moved up/down
And I should see the search results refresh and show related songs based on the last song in the tracklist
And I should see the harmonic keys suggestion card update if needed
```
```
Given I have selected songs from the search Sidebar
When I click the button to use a song as the stem for related song suggestions
Then I should see the search results refresh and show songs related to that song
And I should see the harmonic keys suggestion card update
And I should see a highlight/border around the song being used as the stem for the search
```

**Requirements:**
- After searching for a song, clicking a search result SongCard will add it to the TracklistTable.
- Adding a song to the TracklistTable triggers another search based off the selected song
  - Searches using the selected song's primary artist and the primary artist's top 3 related artists (ranked by popularity) https://developer.spotify.com/documentation/web-api/reference/artists/get-related-artists/
  - Multiple songs can be repeatedly added to the tracklist, each triggering another search
  - At the bottom of the tracklist, show a shadow/faded card displaying harmonic keys based on key of the last track in the tracklist (save array of harmonic keys in store) 
- Ability to move a song in the TracklistTable up/down
  - The Sidebar search results are based on the song at the bottom of the tracklist
  - Therefore moving a song up/down in the tracklist triggers another search (with a rate limit?)
- Ability to remove a song from the TracklistTable
- Ability to manually select a song to stem the search from
- Highlight/border around the song being used as the stem for the related song suggestions

**Subtasks:**
- [x] Implement onClick for clicking a search result SongCard to add it to the tracklist
- [x] Create TracklistTable component
- [x] Implement ability to remove songs from tracklist
- [x] Create TracklistButtons component(s)
- [x] Implement ability to move songs up/down in the tracklist
- [ ] Implement related songs search based off bottom of tracklist/selected song
- [ ] Implement ability to manually select a song to stem the search from
- [ ] Create harmonic key suggestion card
